version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: partido_db
      POSTGRES_USER: partido_db_user
      POSTGRES_PASSWORD: partido_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
